<?php
// Explicit operation → domain service map. HTTP names remain compatible with v1.
return [
    'business.settings' => [\Ternus\Support\Business::class, 'save'],
    'master.save' => [\Ternus\Modules\MasterData\MasterDataService::class, 'save'],
    'master.bulk' => [\Ternus\Modules\MasterData\MasterDataService::class, 'bulk'],
    'user.save' => [\Ternus\Modules\Users\UsersService::class, 'save'],
    'settings' => [\Ternus\Modules\Settings\SettingsService::class, 'save'],
    'receive' => [\Ternus\Modules\Receiving\ReceivingService::class, 'receive'],
    'production.start' => [\Ternus\Modules\Production\ProductionService::class, 'start'],
    'production.complete' => [\Ternus\Modules\Production\ProductionService::class, 'complete'],
    'transfer.send' => [\Ternus\Modules\Transfers\TransfersService::class, 'send'],
    'transfer.receive' => [\Ternus\Modules\Transfers\TransfersService::class, 'receive'],
    'quote.create' => [\Ternus\Modules\Sales\SalesService::class, 'create'],
    'order.create' => [\Ternus\Modules\Sales\SalesService::class, 'create'],
    'quote.accept' => [\Ternus\Modules\Sales\SalesService::class, 'acceptQuote'],
    'quote.convert' => [\Ternus\Modules\Sales\SalesService::class, 'convertQuote'],
    'order.confirm' => [\Ternus\Modules\Sales\SalesService::class, 'confirmOrder'],
    'order.cancel' => [\Ternus\Modules\Sales\SalesService::class, 'cancelOrder'],
    'ship' => [\Ternus\Modules\Shipping\ShippingService::class, 'ship'],
    'invoice.create' => [\Ternus\Modules\Invoices\InvoicesService::class, 'create'],
    'invoice.issue' => [\Ternus\Modules\Invoices\InvoicesService::class, 'issue'],
    'pay' => [\Ternus\Modules\Payments\PaymentsService::class, 'record'],
    'credit' => [\Ternus\Modules\Payments\PaymentsService::class, 'record'],
    'refund' => [\Ternus\Modules\Payments\PaymentsService::class, 'record'],
    'return' => [\Ternus\Modules\Returns\ReturnsService::class, 'receive'],
    'return.release' => [\Ternus\Modules\Returns\ReturnsService::class, 'release'],
    'opname.start' => [\Ternus\Modules\Stocktakes\StocktakesService::class, 'start'],
    'opname.submit' => [\Ternus\Modules\Stocktakes\StocktakesService::class, 'submit'],
    'opname.approve' => [\Ternus\Modules\Stocktakes\StocktakesService::class, 'review'],
    'opname.cancel' => [\Ternus\Modules\Stocktakes\StocktakesService::class, 'review'],
    'asset.create' => [\Ternus\Modules\OfficeAssets\OfficeAssetsService::class, 'create'],
    'asset.event' => [\Ternus\Modules\OfficeAssets\OfficeAssetsService::class, 'recordEvent'],
];
